version: "2"
services:
  steptember-scraper:
    image: steptember-scraper
    restart: always
    depends_on:
    - db
    links:
    - db
    env_file:
    - steptember.env
    - mysql.env
  db:
    image: mysql:5.7
    restart: always
    volumes:
    - ./mysql:/var/lib/mysql
    env_file:
    - mysql.env
  adminer:
    image: adminer
    restart: always
    links:
    - db
    ports:
    - 8080:8080
  grafana:
    image: steptember-grafana
    ports:
    - 3000:3000
    volumes:
    - ./grafana:/var/lib/grafana
    depends_on:
    - db
    links:
    - db
    restart: always
    env_file:
    - mysql.env
    environment:
    - GF_SECURITY_ADMIN_PASSWORD=secret